---
title: "Covid cases and deaths for selected countries and months"
author: "Marc A.T. Teunis"
date: "`r Sys.time()`"
runtime: shiny
output:
  html_document
params:
  geo_id: NL DE
  months_from_to: September December
  year: 2020
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = FALSE
  
  )
```

## Packages
```{r, echo=TRUE}
library(utils)
library(tidyverse)
library(tools)
library(glue)
library(blscrapeR)
```

## Data
Download data from European Center for Disease Prevention and Control [ECDC](https://www.ecdc.europa.eu/en)
```{r, echo=TRUE}
## Read data from public url to csv file
data <- readr::read_csv(
  "https://opendata.ecdc.europa.eu/covid19/casedistribution/csv/data.csv", 
  na = c("", " "))
data
```


## Interactive plot
```{r, fig.height=25, fig.width=18}
source(
  here::here(
    "app",
    "shiny",
    "app.R"
  )
)

covid_app() 
```


## Selections
```{r, results='asis'}
m_names <- str_split(tolower(params$months_from_to), pattern = " ") %>% 
    unlist() %>%
    enframe() 

cat("The data was filtered for",
firstupper(m_names$value[1]), "to", firstupper(m_names$value[2]), 
"in", params$year)
```

```{r, results='asis'}
geo_ids <- str_split(string = params$geo_id, pattern = " ") %>% unlist()

countries <- data %>%
  dplyr::filter(geoId %in% geo_ids) %>%
  dplyr::select(countriesAndTerritories) %>%
  unlist() %>%
  unique() %>%
  as.character()

cat("The data is displayed for", glue_collapse(countries, ", ", last = " and "))
```

## Data cleaning
```{r, echo=TRUE}
data <- data %>%
  mutate(
    date = lubridate::dmy(dateRep),
    ) %>%
  separate(
    col = date, 
    into = c("year", "month", "day"), remove = FALSE) %>%
  mutate(
    month = as.integer(month)
  )

## Filter for `r params$month` and `r params$geo_id`
## create a conversion table to go from month name to month integer
convert_months <- tibble(
  month = c(
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december"),
  month_number = c(1:12))

  month_id <- convert_months %>%
    dplyr::filter(
      month %in% m_names$value) 
id <- c(min(month_id$month_number): max(month_id$month_number))

data_filter <- data %>%
  dplyr::filter(
    month %in% id,
     geoId %in% geo_ids
)
  
char_col <- map_lgl(
  .x = data_filter,
  .f = is.numeric 
)

country_names <- data_filter$countriesAndTerritories %>% unique() %>%
  paste(collapse = ", ")

Caps <- function(x) {
s <- strsplit(x, " ")[[1]]
paste(toupper(substring(s, 1,1)), substring(s, 2),
sep="", collapse=" ")
}

range <- data_filter$month %>% unique() %>% enframe() %>%
  arrange(value)

month_df <- left_join(range, convert_months, by = c("value" = "month_number")) %>%
  dplyr::mutate(month = firstupper(month))

min_month <- month_df %>%
  dplyr::filter(value == min(month_df$value))

countries_vec <- str_split(
  country_names, 
  pattern = ",", 
  simplify = FALSE
  ) %>%
  unlist() %>%
  trimws() %>%
  blscrapeR::firstupper()  
  

max_month <- month_df %>%
  dplyr::filter(value == max(month_df$value))

cap_cases <- paste(
  "COVID-19 positive cases from", 
  min_month$month, "to", max_month$month,
  "for", glue_collapse(countries_vec, ", ", last = " and ")
)

cap_deaths <- paste(
  "COVID-19 related deaths from", 
  min_month$month, "to", max_month$month,
  "for", glue_collapse(countries_vec, ", ", last = " and ")
)


data_filter  
```

## Cases
```{r, fig.cap=cap_cases, echo=TRUE}
Sys.setlocale("LC_TIME", "English")
plot_cases <- data_filter %>%
  na.omit() %>%
  ggplot(aes(x = date, y = cases_weekly)) +
  geom_point(aes(colour = geoId)) +
  geom_line(aes(group = geoId, colour = geoId)) +
  xlab("Date") +
  ylab("COVID-19 positive tested cases") +
  scale_x_date(breaks="month", date_labels = "%b") +
  xlab(NULL) +
  theme_bw()

plot_cases
```

## Deaths
```{r, fig.cap=cap_deaths, echo=TRUE}
## setting month abbreviations to "English"
Sys.setlocale("LC_TIME", "English")

plot_deaths <- data_filter %>%
  ggplot(aes(x = date, y = deaths_weekly)) +
  geom_point(aes(colour = geoId)) +
  geom_line(aes(group = geoId, colour = geoId))  +
  xlab("Date") +
  ylab("COVID-19 related deaths") +
  scale_x_date(breaks="month", date_labels = "%b") +
  xlab(NULL) +
  theme_bw()

plot_deaths

```

